test-guru/config/routes.rb
Rails.application.routes.draw do

  root to: 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout}

  get 'sessions/new'
  get 'session/new'
  get 'users/new'

  #delete :logout, to: 'sessions#destroy'

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :test_passages, only: %i[show update] do
    get :result, on: :member
  end

  namespace :admin do
    resources :tests do
      resources :questions, except: :index, shallow: true do
        resources :answers, except: :index, shallow: true
      end
    end
  end



  get '/tests/:category/:title', to: 'tests#search'
end

test-guru/app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  scope :right_ones, -> { where(correct: true) }

  validate :validate_answers_number, on: :create
  validates :body, presence: true

  private

  def validate_answers_number
    errors.add(:question) if question.answers.count >= 4
  end
end

test-guru/app/controllers/admin/answers_controller.rb
class Admin::AnswersController < Admin::BaseController
  before_action :find_question, only: %i[new create]
  before_action :find_answer, only: %i[show edit update destroy]

  def show;end

  def new
    @answer = @question.answers.new
  end

  def edit;end

  def create
    @answer = @question.answers.new(answer_params)

    if @answer.save
      redirect_to admin_answer_path(@answer)
    else
      render :new
    end
  end

  def update
    if @answer.update(answer_params)
      redirect_to admin_answer_path(@answer)
    else
      render :edit
    end
  end

  def destroy
    @answer.destroy
    redirect_to admin_question_path(@answer.question)
  end

  private

    def find_answer
      @answer = Answer.find(params[:id])
    end

    def answer_params
      params.require(:answer).permit(:body, :correct)
    end

    def find_question
      @question = Question.find(params[:question_id])
    end
end

test-guru/app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :find_question, only: %i[new create]
  before_action :find_answer, only: %i[show edit update destroy]

  def show;end

  def new
    @answer = @question.answers.new
  end

  def edit;end

  def create
    @answer = @question.answers.new(answer_params)

    if @answer.save
      redirect_to @answer
    else
      render :new
    end
  end

  def update
    if @answer.update(answer_params)
      redirect_to @answer
    else
      render :edit
    end
  end

  def destroy
    @answer.destroy
    redirect_to @answer.question
  end

  private

    def find_answer
      @answer = Answer.find(params[:id])
    end

    def answer_params
      params.require(:answer).permit(:body, :correct)
    end

    def find_question
      @question = Question.find(params[:question_id])
    end
end

test-guru/app/helpers/answers_helper.rb
module AnswersHelper
  MAX_NUMBER_OF_ANSWERS = 4

  def can_add_answer_to_this_question?(question)
    question.answers.count < MAX_NUMBER_OF_ANSWERS
  end
end

test-guru/app/views/admin/answers/_answer.html.erb
<li>
    <%= answer.body %><br>
    <%= link_to 'Show', admin_answer_path(answer) %> |
    <%= link_to 'Edit', edit_admin_answer_path(answer) %> |
    <%= link_to 'Delete',
                    admin_answer_path(answer),
                    method: :delete,
                    data: { confirm: 'Are you sure?'} %>
</li>

test-guru/app/views/admin/answers/_form.html.erb
<%= form_with(model: [:admin, @question, @answer], local: true) do |form| %>
  <% render 'shared/errors', resource: @answer %>

  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body, id: :answer_body, rows: 7, cols: 60 %>
  </p><br>

  <p>
    <%= form.label :correct %><br>
    <%= form.check_box :correct, id: :answer_correct %>
  </p><br>

  <p><%= form.submit %></p>
<% end %>

test-guru/app/views/admin/answers/edit.html.erb
<h1>Editing Answer</h1>

<p>
  <%= @answer.question.text %>
</p>

<%= render 'form' %>
<%= link_to 'Back', admin_question_path(@answer.question) %>

test-guru/app/views/admin/answers/new.html.erb
<h1>New Answer</h1>

<p>
  <%= @question.text %>
</p>

<%= render 'form' %>
<%= link_to 'Back', admin_question_path(@question) %>

test-guru/app/views/admin/answers/show.html.erb
<h1>Question</h1>

<p>
  <%= @answer.question.text%>
</p>

<p>
  <b>Answer:</b>
  <%= @answer.body %>
</p>

<p>
  <b>Correct:</b>
  <%= @answer.correct %>
</p>

<%= link_to 'Back', admin_question_path(@answer.question) %>