test-guru/config/routes.rb
Rails.application.routes.draw do

  root to: 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout}

  get 'sessions/new'
  get 'session/new'
  get 'users/new'

  #delete :logout, to: 'sessions#destroy'

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :test_passages, only: %i[show update] do
    get :result, on: :member
  end

  namespace :admin do
    resources :tests do
      resources :questions, except: :index, shallow: true do
        resources :answers, except: :index, shallow: true
      end
    end
  end



  get '/tests/:category/:title', to: 'tests#search'
end

test-guru/app/views/shared/_add_answer_button.html.erb
<% if can_add_answer_to_this_question?(question) then %>
  <%= link_to 'Add answer', new_admin_question_answer_path(question)%>
<% end %>

test-guru/app/views/shared/_add_question_button.html.erb
<% if can_add_question_to_this_test?(test) then %>
  <%= link_to 'Add question', new_admin_test_question_path(test)%>
<% end %>

test-guru/app/views/shared/_errors.html.erb
<% if resource.errors.present? %>
  <div class="">
    <h2><%= pluralize(resource.errors.count, 'error') %> detected:</h2>

    <ul>
      <% resource.errors.full_messages.each do |message|%>
        <li><%= message %></li>
      <% end %>
    </ul>

  </div>
<% end %>

test-guru/app/views/shared/_flash.html.erb
<% flash.each do |key, message| %>
  <%= content_tag :p, message, class: "flash #{key}" %>
<% end %>

test-guru/app/views/shared/_flash_massage.html.erb
<p class='flash <%= type %>'> <%=flash[type]%> </p>

test-guru/app/views/shared/_flash_message.html.erb
<p class='flash <%= type %>'> <%=flash[type]%> </p>

test-guru/app/views/shared/_footer.html.erb
<footer>
  <br><br><br><br><br>
  <strong><%= current_year %></strong>
  <strong>Author: Mikhail Pevzner </strong>
  <h4>Project <a href="<%= github_url("pevzner47", "Ruby_on_real_Rails") %>">Test-Guru</a></h4>
  <h4>Приложение для создание и прохождения тестов</h4>
  <a href="http://thinknetica.com">Учебный проект в онлайн-школе Thinknetica</a>
</footer>

test-guru/app/views/shared/_test.html.erb
<tr>
  <td><%= test.title %></td>
  <td><%= test_level(test) %></td>
  <td align="center"><%= test.questions.count %></td>
  <td><%= link_to 'Show', test_path(test) %></td>
  <td><%= link_to 'Edit', edit_test_path(test) %></td>
  <td><%= link_to 'Delete',
                  test_path(test),
                  method: :delete,
                  data: { confirm: 'Are you sure?'} %>
  </td>
</tr>

test-guru/app/views/shared/edit.html.erb
<h1>Edit <%= @test.title %></h1>

<%= render 'form' %>
<%= link_to 'Back to tests', tests_path %>

test-guru/app/views/shared/index.html.erb
<h1>Tricky Tests</h1>
<p>
  <%= link_to 'New test', new_test_path %>
</p>

<table>
  <tr>
    <th>Title</th>
    <th>Level</th>
    <th>Number of questions</th>
    <th colspan="3">Actions</th>
  </tr>

  <%= render @tests %>
</table>

test-guru/app/views/shared/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @test.title %>
</p>

<p>
  <strong>Level:</strong>
  <%= @test.level %>
</p>

<p>
  <table>
    <%= render @questions %>
  </table>
</p>

<%= render 'shared/add_question_button', test: @test %>
<%= link_to 'Edit this test', edit_test_path(@test)%>
<%= link_to 'Back to tests', tests_path %>