test-guru/config/routes.rb
Rails.application.routes.draw do

  root to: 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout}

  get 'sessions/new'
  get 'session/new'
  get 'users/new'

  #delete :logout, to: 'sessions#destroy'

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :test_passages, only: %i[show update] do
    get :result, on: :member
  end

  namespace :admin do
    resources :tests do
      resources :questions, except: :index, shallow: true do
        resources :answers, except: :index, shallow: true
      end
    end
  end



  get '/tests/:category/:title', to: 'tests#search'
end

test-guru/app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test, optional: true
  has_many :answers, dependent: :destroy # при удаении вопроса удаляется ответ
  has_many :test_passages, foreign_key: "current_question_id", dependent: :nullify
  has_many :users, through: :test_passages

  validates :text, presence: true

end

test-guru/app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::BaseController
  before_action :find_test, only: %i[create new]
  before_action :find_question, only: %i[show destroy edit update]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_question_not_found

  def show; end

  def create
    @question = @test.questions.new(question_params)
    if @question.save
      redirect_to admin_question_path(@question)
    else
      render :new
    end
  end

  def new
    @question = @test.questions.new
  end

  def destroy
    @question.destroy
    redirect_to admin_test_path(@question.test)
  end

  def edit; end

  def update
    if @question.update(question_params)
      redirect_to admin_question_path(@question)
    else
      render :edit
    end
  end

  private

  def question_params
    params.require(:question).permit(:text)
  end

  def find_test
    @test = Test.find(params[:test_id])
  end

  def find_question
    @question = Question.find(params[:id])
  end

  def rescue_with_question_not_found
    render plain: 'Question not found'
  end
end

test-guru/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_test, only: [:create, :new]
  before_action :find_question, only: [:show, :destroy, :edit, :update]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_question_not_found

  def show; end

  def create
    @question = @test.questions.new(question_params)
    if @question.save
      redirect_to @question
    else
      render :new
    end
  end

  def new
    @question = @test.questions.new
  end

  def destroy
    @question.destroy
    redirect_to tests_path
  end

  def edit; end

  def update
    if @question.update(question_params)
      redirect_to @question
    else
      render :edit
    end
  end

  private

  def question_params
    params.require(:question).permit(:text)
  end

  def find_test
    @test = Test.find(params[:test_id])
  end

  def find_question
    @question = Question.find(params[:id])
  end

  def rescue_with_question_not_found
    render plain: 'Question not found'
  end
end

test-guru/app/helpers/questions_helper.rb
module QuestionsHelper
  MAX_NUMBER_OF_QUESTIONS = 10
  ACTION_HEADER = { false => "Create New", true => "Edit"}

  def can_add_question_to_this_test?(test)
    test.questions.count < MAX_NUMBER_OF_QUESTIONS
  end

  def question_header(question)
    "#{ACTION_HEADER[question.persisted?]} '#{question.test.title}' Question"
  end
end

test-guru/app/views/admin/questions/_form.html.erb
<%= form_with model: [:admin, @test, @question], local: true do |form| %>
  <%= render 'shared/errors', resource: @question %>
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text, id: :question_text %>
  </p><br>

  <p><%= form.submit %></p>
<% end %>

test-guru/app/views/admin/questions/_header.html.erb
<h1>
  <%= question_header(@question) %>
</h1>

test-guru/app/views/admin/questions/_question.html.erb
<tr>
  <td><%= question.text %></td>
  <td><%= link_to 'Show', admin_question_path(question) %></td>
  <td><%= link_to 'Edit', edit_admin_question_path(question) %></td>
  <td><%= link_to 'Delete',
                  admin_question_path(question),
                  method: :delete,
                  data: { confirm: 'Are you sure?'} %>
  </td>
</tr>

test-guru/app/views/admin/questions/edit.html.erb
<%= render 'header' %>
<%= render 'form' %>
<%= link_to 'Back to this test', admin_test_path(@question.test) %>

test-guru/app/views/admin/questions/index.html.erb
<h1>Questions from the test "<%= @test.title %>" </h1>

<table>
  <tr>
    <th>Text</th>
    <th colspan="3">Actions</th>

  <%= render @questions %>
</table>

<%= render 'shared/add_question_button', test: @test %>
<%= link_to 'To tests', admin_tests_path %>

test-guru/app/views/admin/questions/new.html.erb
<%= render 'header' %>
<%= render 'form' %>
<%= link_to 'Back to this test', admin_test_path(@test) %>

test-guru/app/views/admin/questions/show.html.erb
<p>
  <strong>Text:</strong>
  <%= @question.text %>
</p>

<p>
  <strong>from test:</strong>
  <%= @question.test.title %>
</p>

<h2>Answers</h2>

<%= render 'shared/add_answer_button', question: @question %>

<ol>
  <%= render @question.answers %>
</ol>

<%= link_to 'Edit', edit_admin_question_path(@question)%>
<%= link_to 'Back to this test', admin_test_path(@question.test) %>
<%= link_to 'Delete',
                admin_question_path(@question),
                method: :delete,
                data: { confirm: 'Are you sure?'} %>