test-guru/config/routes.rb
Rails.application.routes.draw do

  root to: 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout}

  get 'sessions/new'
  get 'session/new'
  get 'users/new'

  #delete :logout, to: 'sessions#destroy'

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :test_passages, only: %i[show update] do
    get :result, on: :member
  end

  namespace :admin do
    resources :tests do
      resources :questions, except: :index, shallow: true do
        resources :answers, except: :index, shallow: true
      end
    end
  end



  get '/tests/:category/:title', to: 'tests#search'
end

test-guru/app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test, optional: true
  has_many :answers, dependent: :destroy # при удаении вопроса удаляется ответ
  has_many :test_passages, foreign_key: "current_question_id", dependent: :nullify
  has_many :users, through: :test_passages

  validates :text, presence: true

end

test-guru/app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: "Question", optional: true

  before_validation :before_validation_find_current_question

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)
    save!
  end

  def completed?
    current_question.nil?
  end

  def succes_rate
    (self.correct_questions.to_f / self.test.questions.count.to_f * 100).round
  end

  def passed?
    succes_rate >= 85
  end

  def current_question_nubmer
    self.test.questions.order(:id).where('id <= ?', self.current_question.id).count
  end

  private

  def before_validation_find_current_question
    self.current_question = next_question
  end

  def correct_answer?(answer_ids)
    correct_answer_count = correct_answer.count

    correct_answer_count == answer_ids.count && (correct_answer_count == correct_answer.where(id: answer_ids).count)
  end

  def next_question
    new_record? ? test.questions.first : test.questions.order(:id).where('id > ?', self.current_question.id).first
  end

  def correct_answer
    self.current_question.answers.right_ones
  end
end

test-guru/app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_test_passage, only: %i[show result update]

  def show; end

  def result; end

  def update
    @test_passage.accept!(params[:answer_ids])
    if @test_passage.completed?
      TestsMailer.completed_test(@test_passage).deliver_now
      redirect_to result_test_passage_path(@test_passage)
    else
      render :show
    end
  end

  private

  def find_test_passage
    @test_passage = TestPassage.find(params[:id])
  end
end

test-guru/app/helpers/test_passages_helper.rb
module TestPassagesHelper
  def passage_status
    "#{@test_passage.current_question_nubmer} question out of #{@test_passage.test.questions.count}"
  end

  def succes_rate_style
    @test_passage.passed? ? 'test_passed' : 'test_failed'
  end

  def result_message
    @test_passage.passed? ? 'You have successfully passed the test' : 'Test failed'
  end
end

test-guru/app/views/test_passages/_message_test_passage.html.erb
<strong>You answered
  <strong class="<%= succes_rate_style %>" >
    <%= @test_passage.succes_rate %>%
  </strong>
 of the questions correctly
</strong>

<div class="<%= succes_rate_style %>">
  <%= result_message %>
</div>

test-guru/app/views/test_passages/result.html.erb
<h1>The '<%= @test_passage.test.title %>' Test was Compiled!</h1>

<%= render 'message_test_passage' %>

<%= link_to 'Back to test list', tests_path %>

test-guru/app/views/test_passages/show.html.erb
<h1>Passing the '<%= @test_passage.test.title %>' Test</h1>

<p>
  <%= passage_status %>
</p>

<b>
  <%= @test_passage.current_question.text %>
</b>

<%= form_with url: test_passage_path(@test_passage), local: true, method: :put do |form| %>
  <%= form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :body, include_hidden: false do |b| %>
    <p>
      <%= b.check_box id: "answer_ids#{b.object.id}" %>
      <%= b.label %>
    </p>
  <% end %>

  <p><%= form.submit 'Next' %></p>
<% end %>